export default function Disclaimer() {
  return (
    <div className="container mx-auto px-6 lg:px-12 py-12 mt-14" >
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold text-foreground mb-8">Disclaimer</h1>
        <div className="prose prose-gray dark:prose-invert max-w-none">
          <p className="text-lg text-muted-foreground mb-6">Last updated: {new Date().toLocaleDateString()}</p>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">General Information</h2>
            <p className="text-muted-foreground mb-4">
              The information provided by AI Career Coach is for general informational purposes only. All information is
              provided in good faith, however we make no representation or warranty of any kind regarding the accuracy,
              adequacy, validity, reliability, or completeness of any information.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">AI-Generated Content</h2>
            <p className="text-muted-foreground mb-4">
              Our AI career coaching recommendations are generated by artificial intelligence and should be considered
              as guidance only. Career decisions should be made based on your own judgment and consideration of your
              unique circumstances.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">Professional Advice</h2>
            <p className="text-muted-foreground mb-4">
              AI Career Coach does not provide professional career counseling services. For specific career advice,
              please consult with qualified career counselors or professional advisors.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">External Links</h2>
            <p className="text-muted-foreground mb-4">
              Our website may contain links to external websites. We have no control over the content and nature of
              these sites and are not responsible for their content or privacy practices.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">Changes to Disclaimer</h2>
            <p className="text-muted-foreground mb-4">
              We reserve the right to update this disclaimer at any time. Changes will be effective immediately upon
              posting on this page.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-foreground mb-4">Contact Us</h2>
            <p className="text-muted-foreground">
              If you have any questions about this Disclaimer, please contact us at info@aicareercoach.com
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
